import Link from 'next/link';
import { Suspense } from 'react';

export default function HomePage() {
  return (
    <div className="flex flex-col gap-8">
      <section className="flex flex-col gap-4">
        <h1 className="text-3xl font-semibold text-slate-900">Welcome to the Menmo Grants Portal</h1>
        <p className="text-base text-slate-600">
          Sign in with your Azure Active Directory credentials to manage your organization profile, review grant
          recommendations generated by the Menmo data platform, and monitor upcoming opportunities.
        </p>
        <p className="text-base text-slate-600">
          The dashboard automatically pulls matched and upcoming grants from the secured Azure Functions APIs. Filter by
          eligibility, sort by deadline or match confidence, and explore source citations that explain why each grant is a
          good fit.
        </p>
        <div className="flex flex-wrap gap-3">
          <Suspense fallback={null}>
            <Link
              href="/dashboard"
              className="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-blue-700"
            >
              Go to dashboard
            </Link>
          </Suspense>
          <Link
            href="/profile"
            className="rounded-md border border-blue-600 px-4 py-2 text-sm font-semibold text-blue-600 hover:bg-blue-50"
          >
            Update profile
          </Link>
        </div>
      </section>
      <section className="grid gap-6 md:grid-cols-2">
        <div className="rounded-2xl border border-slate-200 p-6">
          <h2 className="text-xl font-semibold text-slate-900">Secure sign-in</h2>
          <p className="mt-2 text-sm text-slate-600">
            Azure AD protects access to your data. The portal exchanges tokens via MSAL and includes them on each API call
            to Azure Functions, ensuring that only authorized staff members can view matched funding opportunities.
          </p>
        </div>
        <div className="rounded-2xl border border-slate-200 p-6">
          <h2 className="text-xl font-semibold text-slate-900">Actionable insights</h2>
          <p className="mt-2 text-sm text-slate-600">
            Each grant card highlights eligibility signals, deadlines, confidence scores, and citation snippets so you can
            quickly understand why an opportunity matters.
          </p>
        </div>
      </section>
    </div>
  );
}
