import { ProfileForm } from '@/components/ProfileForm';
import { AuthenticatedTemplate, UnauthenticatedTemplate } from '@azure/msal-react';

export default function ProfilePage() {
  return (
    <div className="flex flex-col gap-8">
      <header className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold text-slate-900">Organization profile</h1>
        <p className="text-base text-slate-600">
          Keep your organization information current to improve the quality of grant matches generated by Menmo.
        </p>
      </header>
      <AuthenticatedTemplate>
        <ProfileForm />
      </AuthenticatedTemplate>
      <UnauthenticatedTemplate>
        <div className="rounded-2xl border border-blue-100 bg-blue-50 p-6 text-center text-slate-700">
          <p className="text-base font-medium">Sign in with Azure AD to manage your profile.</p>
        </div>
      </UnauthenticatedTemplate>
    </div>
  );
}
